config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  if Rails.env.production?
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username),
                                                  ::Digest::SHA256.hexdigest(ENV['SIDEKIQ_USERNAME'])) &
        ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password),
                                                    ::Digest::SHA256.hexdigest(ENV['SIDEKIQ_PASSWORD']))
    end
  end
  mount Sidekiq::Web, at: '/sidekiq'
  get 'detail_scheduling/index', to: 'detail_scheduling#index', as: :detail_scheduling_index
  get 'detail/index', to: 'detail_scheduling#detail', as: :detail_index
  get 'sus_card/index', to: 'detail_scheduling#scheduling_card_sus', as: :sus_card_index
  get 'regulations_queue', to: 'regulations_queue#index'
  get 'regulation_queue/:id', to: 'regulations_queue#show', as: :regulation_queue
  get 'procedures', to: 'regulations_queue#procedures_by_cbo'

  # get 'detail_scheduling/test'
  root 'main#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # If any other non defined route were accessed, redirect to 404 page
  match '*path', via: :all, to: redirect('/404')
end

app/models/app.rb
class App < ApplicationRecord
  attr_accessor :recaptcha_error
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/regulation_queue.rb
class RegulationQueue < ApplicationRecord

  self.primary_key = :regulation_id
  self.table_name = :regulations_queue

  # Filtra apenas regulação que tenham posição na fila e ordena pela posição como integer.
  # As regras repassadas para como uma regulação obtêm posição na fila foram:
  # - Regulações com situação Agendada, Vencida e Pendente.
  # - Regulações com situação Em análise, mas que tem mais de uma crítica de agendamento.
  # - Regulações com data_entrada igual a hoje. (a não ser que a rotina de ordenação da fila tenha sido executada manualmente)
  # * crítica de agendamento : Ex.: 
  #   - Sexo incompatível com o procedimento
  #   - Idade incompatível com o procedimento
  #   - Procedimento com demanda reprimida
  # Entretanto, as críticas de agendamento não estão disponíveis e haviam outros casos de situações com posição nula fora
  # dos citados anteriormente. Por isso é realizado o filtro por posicao fila não nula.
  default_scope {where(Arel.sql("fields->>'posicao_fila' != ''")).order(Arel.sql("cast(fields->>'posicao_fila' as integer)  ASC"))}

  # Lista de CBOs com regulações na fila
  # Retorna um Array de [descrição, código] de CBOs
  def self.cbos
    pluck(Arel.sql("fields->'cbo_descricao', fields->'cbo_codigo'")).uniq
  end

  # Lista de procedimentos de um determinado CBO com regulações na fila 
  # Retorna um Array de [nome_procedimento, código_procedimento]
  def self.procedures(cbo_code)
    where("fields->>'cbo_codigo' = ?", cbo_code).pluck(Arel.sql("fields->'procedimento_solicitado', fields->'procedimento_solicitado_codigo'")).uniq
  end

  # Lista de Regulacoes por CBO e Procedimento
  def self.list_by_cbo_and_procedure(cbo, procedure)
    return none unless cbo.present? && procedure.present?

    query = "fields->>'cbo_codigo' = '#{cbo}' and fields->>'procedimento_solicitado_codigo' = '#{procedure}'"
    where(Arel.sql(query))
    .order(Arel.sql("fields->'cbo_descricao', fields->'procedimento_solicitado', fields->'posicao_fila', fields->'data_entrada_fila'"))
  end

  def request_date
    Date.parse(fields["data_entrada_fila"]) if fields["data_entrada_fila"].present?
  end

  def inclusion_date
    Date.parse(fields["data_entrada_fila"]) if fields["data_entrada_fila"].present?
  end
end

app/models/regulation_queue_file.rb
class RegulationQueueFile < ApplicationRecord
  has_one_attached :file
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/detail_scheduling_controller.rb
class DetailSchedulingController < ApplicationController
  def index
    @app = App.new
    if(params[:number_id].present? && params[:number_id].to_i != 0)
      data = PatientService.new.find_patient(params[:number_id])
      @patient_data = data['dados'].present? ? data['dados'][0] : nil
    else
      @patient_data = 'Preencha o número de ID ou da solicitação de regulação localizado no seu comprovante de agendamento.'
    end
  end

  def detail
    if(params[:number_id].present? && params[:number_id].to_i != 0)
      data = PatientService.new.find_patient(params[:number_id])
      @patient_data = data['dados'].present? ? data['dados'][0] : nil
    else
      @patient_data = 'Preencha o número de ID ou da solicitação de regulação localizado no seu comprovante de agendamento.'
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @patient_data }
    end
  end
  def scheduling_card_sus
    if(params[:number_card].present? && params[:number_card].to_i != 0)
      @patient_data = SoapClientService.new(sus_card: params[:number_card]).get_schedules
    else
      @patient_data = 'Preencha o número do cartão SUS usado para o agendamento.'
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @patient_data }
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
  end
end

app/controllers/regulations_queue_controller.rb
include Pagy::Backend
class RegulationsQueueController < ApplicationController
   
  def index
    cbo = params['cbo'] || ''
    procedure = params['procedure'] || ''
    list = RegulationQueue.list_by_cbo_and_procedure(cbo, procedure)
    @update_date = RegulationQueueFile.where(parsed: true).last.try(:updated_at)
    @pagy, @regulations_queue = pagy(list, link_extra: 'data-remote="true"')
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    respond_to do |format|
      format.json { render json: RegulationQueue.find_by_regulation_id(params['id']) }
    end
  end

  def procedures_by_cbo
    respond_to do |format|
      format.json {render json: RegulationQueue.procedures(params['cbo_code'])}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/details_sheduling_helper.rb
module DetailsShedulingHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/detail_scheduling/index.html.erb
<body id="page-top">
<!-- Navigation -->
<nav id="main-navbar" class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
  <div class="container">
    <a class="navbar-brand js-scroll-trigger visible-lg visible-md" href="#page-top"><%= image_tag "white_header.png", class: "img-fluid",size: '100x100' %></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</nav>

<section>
  <div class="container masthead" id="printDiv">
    <div class="card border-primary">
      <div class="card-header"> <div class="row"><div class="col-3"><%= image_tag "logo-fms.png", class: "img-fluid", size: '200x60' %></div><div class="col-9"></div></div></div>
      <div class="card-body">
        <% if @patient_data.present? && (@patient_data["regulacao_id"].present? || @patient_data["agendamento_id"].present?) %>
            <div class="row">
              <div class="col-lg-12 col-xs-12 col-sm-12">
                <h4 class="card-title" style="margin-bottom: 0.1rem">Situação</h4>
                  <% if @patient_data["situacao_fila"]=='Pendente de Informação' || @patient_data["situacao_fila"]=='Pendente' %>
                    <p class="card-text"><strong><span class="badge badge-pill badge-warning"><%= @patient_data["situacao_fila"] %></span></strong></p>
                    <div class="alert alert-dismissible alert-warning">SEU PEDIDO HÁ INFORMAÇÕES INCOMPLETAS. COMPAREÇA IMEDIATAMENTE À SUA UNIDADE BÁSICA DE SAÚDE.</div>
                    <% end %>
                  <% if @patient_data["situacao_fila"]=='Em Análise' %>
                    <p class="card-text" ><strong><span class="badge badge-pill badge-warning"><%= @patient_data["situacao_fila"] %></span></strong></p>
                    <div class="alert alert-dismissible alert-warning">
                      <b>AGUARDE ANALISE DA CENTRAL DO SUS.</b> </div>
                     <% end %>
                  <% if @patient_data["situacao_fila"]=='Liberada para Agendamento' || @patient_data["situacao_fila"]=='Liberada' %>
                    <p class="card-text" ><strong><span class="badge badge-pill badge-warning"><%= @patient_data["situacao_fila"] %></span></strong></p>
                    <div class="alert alert-dismissible alert-warning">
                      <b>SOLICITAÇÃO LIBERADA. COMPAREÇA A UMA UNIDADE BÁSICA DE SAÚDE PARA REALIZAR O AGENDAMENTO.</b> </div>
                    <% end %>
                  <% if @patient_data["situacao_fila"]=='Negada' %>
                    <p class="card-text" ><strong><span class="badge badge-pill badge-danger"><%= @patient_data["situacao_fila"] %></span></strong></p>
                    <div class="alert alert-dismissible alert-danger">
                      <b>REGULAÇÃO NEGADA POR INFORMAÇÕES INCOERENTES. NA DÚVIDA, COMPAREÇA À SUA UNIDADE BÁSICA DE SAÚDE PARA ESCLARECIMENTOS.</b></div>
                    <% end %>
                  <% if @patient_data["situacao_fila"]=='Agendada' %>
                    <p class="card-text" ><strong><span class="badge badge-pill badge-success"><%= @patient_data["situacao_fila"] %></span></strong></p>
                    <div class="alert alert-dismissible alert-success">
                      <b>ENCAMINHAMENTO MARCADO. VÁ IMEDIATAMENTE À SUA UNIDADE BÁSICA DE SAÚDE PARA QUE O COMPROVANTE DE AGENDAMENTO SEJA CARIMBADO E ASSINADO PELO SERVIDOR DO SAME.</b> </div>
                    <% end %>
                  <% if @patient_data["situacao_fila"]=='Marcado Normal' %>
                    <p class="card-text" ><strong><span class="badge badge-pill badge-success"><%= @patient_data["situacao_fila"] %></span></strong></p>
                    <div class="alert alert-dismissible alert-success">
                      <b>ENCAMINHAMENTO MARCADO. VÁ IMEDIATAMENTE À SUA UNIDADE BÁSICA DE SAÚDE PARA QUE O COMPROVANTE DE AGENDAMENTO SEJA CARIMBADO E ASSINADO PELO SERVIDOR DO SAME.</b></div>
                    <% end %>
                  <% if @patient_data["situacao_fila"]=='Conferida' %>
                    <p class="card-text" ><strong><span class="badge badge-pill badge-info"><%= @patient_data["situacao_fila"] %></span></strong></p>
                    <div class="alert alert-dismissible alert-info">SOLICITAÇÃO DE REGULAÇÃO FOI CONFERIDA, NA DÚVIDA, COMPAREÇA A UMA UNIDADE BÁSICA DE SAÚDE PARA ESCLARECIMENTOS.</div>
                    <% end %>
                  <% if @patient_data["situacao_fila"]=='Obito' %>
                    <p class="card-text" ><strong><span class="badge badge-pill badge-danger"><%= @patient_data["situacao_fila"] %></span></strong></p>
                    <div class="alert alert-dismissible alert-danger">O PACIENTE FALECEU, COMPAREÇA A UMA UNIDADE BÁSICA DE SAÚDE PARA ESCLARECIMENTOS.</div>
                    <% end %>
                  <% if @patient_data["situacao_fila"]=='Revalidação' %>
                    <p class="card-text" ><strong><span class="badge badge-pill badge-danger"><%= @patient_data["situacao_fila"] %></span></strong></p>
                    <div class="alert alert-dismissible alert-danger">
                      <b>SOLICITAÇÃO PASSOU MAIS DE 60 DIAS AGUARDANDO AGENDAMENTO. DIRIJA-SE IMEDIATAMENTE À SUA UNIDADE DE SAUDE PARA CONFIRMAÇÃO. OBS: CASO A SOLICITAÇÃO PERMANEÇA MAIS 180 DIAS EM REVALIDAÇÃO ELA SERÁ CANCELADA AUTOMATICAMENTE.</b></div>
                    <% end %>
                  <% if @patient_data["situacao_fila"]=='Vencida' || @patient_data["situacao_fila"]=='Cancelada' %>
                    <p class="card-text" ><strong><span class="badge badge-pill badge-danger"><%= @patient_data["situacao_fila"] %></span></strong></p>
                    <div class="alert alert-dismissible alert-danger">
                      <b>SOLICITAÇÃO CANCELADA. COMPAREÇA A UNIDADE BASICA DE SAÚDE PARA ESCLARECIMENTOS.</b></div>
                    <% end %>
              </div>
            </div>
              <div class="row">
                <table width="100%">
                  <tbody>
                  <tr>
                    <td>
                      <% if @patient_data["data_hora_atendimento"].present? %>
                          <div class="col-lg-6 col-xs-6 col-sm-6">
                            <h4 class="card-title" style="margin-bottom: 0.1rem">Data e hora da consulta marcada</h4>
                            <p class="card-text" style="display: inline;"><%= @patient_data["data_hora_atendimento"].split(" ")[0].to_date.strftime("%d/%m/%Y") %>
                              - <%= @patient_data["data_hora_atendimento"].split(" ")[1] %></p>
                          </div>
                      <% end %>
                    </td>
                    <td>
                      <% if @patient_data["regulacao_id"].present? %>
                          <div class="col-lg-6 col-xs-6 col-sm-6">
                            <h4 class="card-title" style="margin-bottom: 0.1rem">ID de regulação</h4>
                            <p class="card-text" style="display: inline;"><%= @patient_data["regulacao_id"] %></p>
                          </div>
                      <% end %>
                    </td>
                  </tr>
                  <% if (@patient_data["situacao_fila"]=='Agendada' || @patient_data["situacao_fila"]=='Marcado Normal') && @patient_data["agendamento_autorizacao"].present? %>
                  <tr>
                    <td>
                          <div class="col-lg-6 col-xs-6 col-sm-6">
                            <h4 class="card-title" style="margin-bottom: 0.1rem">Autorização do agendamento</h4>
                            <p class="card-text" style="display: inline;"><%= @patient_data["agendamento_autorizacao"] %></p>
                          </div>
                    </td>
                  </tr>
                      <% end %>
                  </tbody>
                </table>
              </div>
            <hr>
                <% if (@patient_data["situacao_fila"]=='Agendada' || @patient_data["situacao_fila"]=='Marcado Normal') && @patient_data["estabelecimento_executante_nome"].present? %>
                    <h4 class="card-title" style="margin-bottom: 0.1rem">Estabelecimento executante da consulta</h4>
                    <p class="card-text" style="display: inline;"><%= @patient_data["estabelecimento_executante_nome"] %></p>
                    <h4 class="card-title" style="margin-bottom: 0.1rem">Endereço do estabelecimento</h4>
                    <p class="card-text" style="display: inline;"><%= @patient_data["estabelecimento_executante_endereco"] %>
                      , <%= @patient_data["estabelecimento_executante_bairro"] %></p>
                <% if @patient_data["estabelecimento_executante_fone1"].present? || @patient_data["estabelecimento_executante_fone2"].present?%>
                    <h4 class="card-title" style="margin-bottom: 0.1rem">Telefones para contato</h4>
                    <p class="card-text" style="display: inline;"><%= @patient_data["estabelecimento_executante_fone1"] %>
                       <%= @patient_data["estabelecimento_executante_fone2"] %></p>
                    <% end%>
                    <hr>
              <% end %>
        <% if (@patient_data["posicao_fila"] && @patient_data["previsao_fila_agendamento"])  %>
          <h4 class="card-title" style="margin-bottom: 0.1rem">Posição da Fila</h4>
          <p class="card-text" style="display: inline;"><strong><%= @patient_data["posicao_fila"] %></strong></p>
          <h4 class="card-title" style="margin-bottom: 0.1rem">Previsão de atendimento</h4>
          <p class="card-text" style="display: inline;"><strong><%= @patient_data["previsao_fila_agendamento"] %></strong></p>
        <% end %>
                <br>
                <br>
                <div class="footer_ass">
                  <center>
                    <h4 class="card-title" style="margin-bottom: 0.1rem">_________________________________________________</h4>
                    <p class="card-text" style="display: inline;">Assinatura e Carimbo do Responsável pelo Agendamento</p>
                  </center>
                </div>
            </div>
            <% elsif @patient_data.blank?%>
            <div class="alert alert-dismissible alert-danger">
              <h4 class="card-title">Verifique se o ID ou da solicitação de regulação localizado no seu comprovante de agendamento está correto!</h4>
            </div>
            <% else %>
                <div class="alert alert-dismissible alert-danger">
                  <h4 class="card-title"><%= @patient_data %></h4>
                </div>
            <% end %>
            </div>
       </div>
            <div class="container form-group col-sm-offset-1">
            <% if  @patient_data.present? && @patient_data["regulacao_id"].present? %>
                <button id="buttonImprimir" type="button" class="btn btn-primary">Imprimir</button>
            <% end %>

              <a href="javascript:history.back()" type="button" class="btn btn-primary"><%= t 'helpers.links.back' %></a>
            </div>
    </div>
  </section>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <title><%= Rails.application.config.system_title %></title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('logofms.png'), :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag asset_path('logofms.png'), :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag asset_path('logofms.png'), :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag asset_path('logofms.png'), :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag asset_path('logofms.png'), :rel => 'shortcut icon' %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%#<% if Rails.env.production? %>
        <%#[> Global site tag (gtag.js) - Google Analytics <]%>
        <%#<script async src="https://www.googletagmanager.com/gtag/js?id=UA-141617894-1"></script>%>
        <%#<script>%>
            <%#window.dataLayer = window.dataLayer || [];%>
            <%#function gtag(){dataLayer.push(arguments);}%>
            <%#gtag('js', new Date());%>

            <%#gtag('config', 'UA-141617894-1');%>
        <%#</script>%>
  <%#<% end %>
  </head>

  <body>
    <%= yield %>
  </body>

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white"><%= Rails.application.config.system_footer %></p>
    </div>
  </footer>
</html>

app/views/main/index.html.erb
<body id="page-top">
  <!-- Navigation -->
  <nav id="main-navbar" class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger visible-lg visible-md" href="#page-top"><%= image_tag "white_header.png", class: "img-fluid fms_brand",size: '100x100'  %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link js-scroll-trigger" href="#check_regulation_status"><%= t 'menu.title.check_regulation_status' %></a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#how_perform_search_site"><%= t 'menu.title.how_perform_search_site' %></a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#contacts"><%= t 'menu.title.contacts' %></a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link" href= <%= regulations_queue_path %>><%= t 'menu.title.regulations_queue' %></a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <section id="check_regulation_status" class="masthead">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 mx-auto">
          <div class="card border-primary">
            <div class="card-body">
              <h4 class="card-title"><%= t 'menu.sub_title.enter_regulatory_request_number' %></h4>
              <%= form_tag({controller: 'detail_scheduling', action: 'index'}, method: 'get', class: 'form-horizontal') do %>
                <div class="form-group">
                  <div class="row">
                    <div class="col-lg-11">
                      <%= number_field_tag :number_id, "",class: "form-control",placeholder: "Insira o número aqui" , pattern: "[0-9]+"%>
                    </div>
                    <div class="col-lg-1">
                      <a class="nav-link js-scroll-trigger" href="#how_perform_search_site">
                        <%= octicon "question", height: 36 %>
                      </a>
                    </div>
                  </div>
                </div>

                <div class="form-group col-sm-offset-1">
                  <button type="submit" id="button_busca" class="btn btn-primary">
                    <%= t 'menu.button.seach_button' %>
                  </button>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section>
    <div class="container">
      <div class="row">
        <div class="col-lg-12 mx-auto">
          <div class="card border-primary">
            <div class="card-body">
              <h4 class="card-title"><%= t 'menu.title.regulations_queue' %></h4>
              <p><%= t :section_description, scope: :regulations_queue %></p>
              <%= link_to t('regulations_queue.btn.go_to_regulations_queue'), regulations_queue_path, class: 'btn btn-primary mt-3' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section id="how_perform_search_site">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 mx-auto">
          <div class="card border-primary">
            <div class="card-header"><%= t 'menu.title.how_perform_search_site' %></div>
            <div class="card-body">
              <center>
                <p>O Número da Solicitação de Regulação está localizado no comprovante emitido pelo SAME da UBS, conforme figura abaixo:</p>
                <%= image_tag "how_perform_search_site.png", class: "img-fluid" %>
              </center>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section id="contacts">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 mx-auto">
          <div class="card border-primary">
            <div class="card-header"><%= t 'menu.title.contacts' %></div>
            <div class="card-body">
              <h4 class="card-title"><%= t 'menu.sub_title.ombudsman' %></h4>
              <p class="card-text">Telefone: (86) 3223-2132</p>
              <p class="card-text">WhatsApp: (86) 99446-3321</p>
              <p class="card-text">E-mail: ouvidoriasus@pmt.pi.gov.br</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</body>

app/views/regulations_queue/index.html.erb
<nav id="queue-navbar" class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
  <div class = 'container'>
      <a class="navbar-brand visible-lg visible-md" href="/">
        <%= image_tag "white_header.png", class: "img-fluid fms_brand",size: '100x100'  %>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
              aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="queue_navbar_collapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href= <%= root_path %>><%= t 'menu.title.check_regulation_status' %></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href= <%= regulations_queue_path %>><%= t 'menu.title.regulations_queue' %></a>
          </li>
        </ul>
      </div>
  </div>
</nav>
<div class="container">
  <div class="row masthead">
    <div class="alert alert-info col-12" role="alert">
      <%= t(:info, scope: :regulations_queue, update_date: l(@update_date, format: :long, default: '')) %>
    </div>
    <div class="col">
      <section>
        <div class="card border-primary">
          <div class="card-body">
          <h4 class="card-title"><%= t 'menu.sub_title.select_queue' %></h4>
            <%= form_with(url: regulations_queue_path, method: 'get', class: 'pt-2 form-vertical') do %>
              <div class="form-group row">
                <%= label_tag :cbo, t(:cbo, scope: :regulations_queue), class: "col-form-label"%>
                <%= select_tag(:cbo, options_for_select(RegulationQueue.cbos), 
                              {id: 'cbo_select', include_blank: true, class: 'form-control', aria: { describedby: "cboHelpBlock"}, autocomplete: 'off'}) %>
                <small id="cboHelpBlock" class="form-text text-muted">
                  <%= t(:cbo_help, scope: [:regulations_queue, :help]) %>
                </small>

              </div>
              <div class="form-group row">
                <%= label_tag :procedure, t(:procedure, scope: :regulations_queue), class: "col-form-label"%>
                <%= select_tag(:procedure, [], id: 'procedure_select', class: 'form-control', aria: { describedby: "procedureHelpBlock"}) %>
                <small id="procedureHelpBlock" class="form-text text-muted">
                  <%= t(:procedure_help, scope: [:regulations_queue, :help]) %>
                </small>
              </div>
              <%= submit_tag(t(:submit_queue_filters, scope: %i[regulations_queue btn]), id: 'submit_btn', class: 'btn btn-primary') %>
            <% end %>
          </div>
        </div>
      </section>
    </div>
  </div>
  <section>
    <div class="card">
      <div class="card-body">
        <div class = 'row'>
          <div id = 'regulations_queue_table_container' class="col">
            <%= render "regulations_queue_table" %>
          </div>
        </div>
      </div>
    </div>
  </section>
  <%= render "faq" %>
</div>

app/views/regulations_queue/index.js.erb
<%# empty table %>
$("#regulations_queue_table_container").empty()
<%# renders the updated table %>
$("<%= escape_javascript(render "regulations_queue_table") %>").appendTo("#regulations_queue_table_container");
<%# add event listener for modal activation %>
$('#more_info_modal').on('show.bs.modal', function (event) {
    var button = $(event.relatedTarget)
    var fields = button.data('id'); 
    fetch_regulation_queue_more_field_data(fields)
  })
Pagy.init(document.getElementById('regulations_queue_table_container'));